name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: flake8 Lint
      uses: py-actions/flake8@v1
      with:
          ignore: "E203,E266,E501,W503,F403,F401,E731"
          max-line-length: "79"
          exclude: interpretability
